name: 'Apache2-Setup'

on: push

jobs:
  build:
    name: 'SETUP'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Configure JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Installing Dependencies'
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6 && sudo apt install apache2
      - name: 'Getting IP'
        run: curl ifconfig.me
      - name: 'Save'
        uses: actions/upload-artifact@v1.0.0
