name: 'Teamviewer Setup'

on: push

jobs:
  build:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Configure JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Verifying Submodules'
        uses: textbook/git-checkout-submodule-action@master
      - name: 'Installing Dependencies'
        run: sudo apt update && sudo apt-get install gdebi && sudo apt-get install wget && apt-get install ubuntu-desktop && apt-get install xserver-xorg-video-dummy
      - name: 'Download Teamviewer'
        run: wget https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      - name: 'Installing Teamviewer'
        run: sudo gdebi teamviewer_amd64.deb
      - name: 'Get Partner ID'
      - run: teamviewer license accept && teamviewer daemon enable && teamviewer daemon start && teamviewer passwd thenewpassword && teamviewer info
